"""your migration message here

Revision ID: 09a4df2d2b90
Revises: 5b320b545de1
Create Date: 2026-02-08 16:59:18.902969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09a4df2d2b90'
down_revision: Union[str, Sequence[str], None] = '5b320b545de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - SAFE VERSION - only removes column comments."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # KEEP ONLY these safe operations (removing column comments)
    op.alter_column('admins', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last login timestamp',
               existing_nullable=True)
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('admins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=True)
    
    # Keep applicant column comment removals (safe)
    op.alter_column('applicants', 'nin_number',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='National Identity Number (optional)')
    op.alter_column('applicants', 'nin_slip',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='NIN slip upload path (optional)')
    
    # DO NOT drop any columns, constraints, or indexes!
    # Remove all other operations that drop things
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - SAFE VERSION."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore column comments only
    op.alter_column('applicants', 'nin_slip',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='NIN slip upload path (optional)',
               existing_comment=None)
    op.alter_column('applicants', 'nin_number',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='National Identity Number (optional)',
               existing_comment=None)
    
    op.alter_column('admins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Record last update timestamp',
               existing_nullable=True)
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('admins', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment='Last login timestamp',
               existing_nullable=True)
    # ### end Alembic commands ###