"""payment error fix - SAFE VERSION

Revision ID: 0e5facd13b7d
Revises: 09a4df2d2b90
Create Date: 2026-02-09 12:00:49.884006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e5facd13b7d'
down_revision: Union[str, Sequence[str], None] = '09a4df2d2b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - SAFE VERSION - only minimal safe changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # KEEP ONLY these safe operations:
    
    # 1. Make columns nullable (safe operation)
    op.alter_column('applicants', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('applicants', 'state_of_residence',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applicants', 'lga',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('applicants', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('applicants', 'passport_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applicants', 'selected_reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    
    # 2. Remove table comment (safe)
    op.drop_table_comment(
        'existing_officers',
        existing_comment='Table for existing officers - UPDATED for 2-upload system',
        schema=None
    )
    
    # DO NOT drop any columns, constraints, or indexes!
    # Comment out or remove all drop operations below this line
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - SAFE VERSION."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore table comment
    op.create_table_comment(
        'existing_officers',
        'Table for existing officers - UPDATED for 2-upload system',
        existing_comment=None,
        schema=None
    )
    
    # Restore nullable changes
    op.alter_column('applicants', 'selected_reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('applicants', 'passport_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applicants', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('applicants', 'lga',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('applicants', 'state_of_residence',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applicants', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    
    # DO NOT restore dropped columns - they were never dropped in this safe version
    # ### end Alembic commands ###