"""Add is_verified and application_password to PreApplicant

Revision ID: 151da8f94e2b
Revises: e7065b729a13
Create Date: 2025-07-31 23:46:27.343643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151da8f94e2b'
down_revision: Union[str, Sequence[str], None] = 'e7065b729a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_applicants', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('pre_applicants', sa.Column('application_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_applicants', 'application_password')
    op.drop_column('pre_applicants', 'is_verified')
    # ### end Alembic commands ###
