"""initial_migration

Revision ID: 2a7e1f165613
Revises: 883e2e370739
Create Date: 2026-01-15 09:06:13.380267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7e1f165613'
down_revision: Union[str, Sequence[str], None] = '883e2e370739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add category column to existing_officers (KEEP THIS)
    op.add_column('existing_officers', sa.Column('category', sa.String(length=50), nullable=True, comment='Officer category: MCN (Marshal Core Nigeria), MBT (Marshal Board of Trustees), MBC (Marshal Board Committee)'))
    
    # 2. Create index for category (ADD THIS)
    op.create_index(op.f('ix_existing_officers_category'), 'existing_officers', ['category'], unique=False)
    
    # 3. REMOVE THESE LINES - DO NOT DROP INDEXES
    # op.drop_index(op.f('ix_existing_officers_email'), table_name='existing_officers')
    # op.drop_index(op.f('ix_existing_officers_nin_number'), table_name='existing_officers')
    # op.drop_index(op.f('ix_existing_officers_officer_id'), table_name='existing_officers')
    # op.drop_index(op.f('ix_existing_officers_status'), table_name='existing_officers')
    
    # 4. Keep pre_applicants changes (but fix them if needed)
    op.alter_column('pre_applicants', 'password_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pre_applicants', 'password_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pre_applicants', 'application_submitted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pre_applicants', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'created'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre_applicants', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('pre_applicants', 'application_submitted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pre_applicants', 'password_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pre_applicants', 'password_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    
    # 5. Drop the category index (ADD THIS)
    op.drop_index(op.f('ix_existing_officers_category'), table_name='existing_officers')
    
    # 6. REMOVE THESE LINES - DO NOT RECREATE INDEXES (they were never dropped)
    # op.create_index(op.f('ix_existing_officers_status'), 'existing_officers', ['status'], unique=False)
    # op.create_index(op.f('ix_existing_officers_officer_id'), 'existing_officers', ['officer_id'], unique=True)
    # op.create_index(op.f('ix_existing_officers_nin_number'), 'existing_officers', ['nin_number'], unique=True)
    # op.create_index(op.f('ix_existing_officers_email'), 'existing_officers', ['email'], unique=True)
    
    # 7. Drop the category column
    op.drop_column('existing_officers', 'category')
    # ### end Alembic commands ###