"""Re-add has_paid field

Revision ID: 3d9885d25946
Revises: f4b64385778e
Create Date: 2025-07-30 12:23:17.197690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9885d25946'
down_revision: Union[str, Sequence[str], None] = 'f4b64385778e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('has_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'has_paid')
    # ### end Alembic commands ###
