"""add MyNewModel table

Revision ID: 7995d7e0bbdd
Revises: 0e5facd13b7d
Create Date: 2026-03-19 06:45:16.882352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7995d7e0bbdd'
down_revision: Union[str, Sequence[str], None] = '0e5facd13b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('officer_id', sa.String(length=100), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('pdf_size_kb', sa.Float(), nullable=False),
    sa.Column('num_images', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_uploads_email'), 'image_uploads', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_uploads_email'), table_name='image_uploads')
    op.drop_table('image_uploads')
    # ### end Alembic commands ###
