# add_pre_applicant_fields_for_resume_functionality

"""add_pre_applicant_fields_for_resume_functionality

Revision ID: 82b41e8404ca
Revises: 0ebd7cc64f4e
Create Date: 2025-09-09 12:59:03.814074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b41e8404ca'
down_revision: Union[str, Sequence[str], None] = '0ebd7cc64f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_applicants', sa.Column('payment_reference', sa.String(), nullable=True))
    op.add_column('pre_applicants', sa.Column('password_generated', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('pre_applicants', sa.Column('password_generated_at', sa.DateTime(), nullable=True))
    op.add_column('pre_applicants', sa.Column('password_expires_at', sa.DateTime(), nullable=True))
    op.add_column('pre_applicants', sa.Column('password_used', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('pre_applicants', sa.Column('application_submitted', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('pre_applicants', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('pre_applicants', sa.Column('status', sa.String(), server_default='created', nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE pre_applicants SET password_generated = false WHERE password_generated IS NULL")
    op.execute("UPDATE pre_applicants SET password_used = false WHERE password_used IS NULL")
    op.execute("UPDATE pre_applicants SET application_submitted = false WHERE application_submitted IS NULL")
    op.execute("UPDATE pre_applicants SET status = 'created' WHERE status IS NULL")
    
    # Make new columns NOT NULL after setting defaults
    op.alter_column('pre_applicants', 'password_generated', nullable=False)
    op.alter_column('pre_applicants', 'password_used', nullable=False)
    op.alter_column('pre_applicants', 'application_submitted', nullable=False)
    op.alter_column('pre_applicants', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_applicants', 'status')
    op.drop_column('pre_applicants', 'submitted_at')
    op.drop_column('pre_applicants', 'application_submitted')
    op.drop_column('pre_applicants', 'password_used')
    op.drop_column('pre_applicants', 'password_expires_at')
    op.drop_column('pre_applicants', 'password_generated_at')
    op.drop_column('pre_applicants', 'password_generated')
    op.drop_column('pre_applicants', 'payment_reference')
    # ### end Alembic commands ###