"""Fix applicant model fields

Revision ID: 98deb6cefe88
Revises: a3f14bfa8956
Create Date: 2025-07-25 00:48:47.210654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98deb6cefe88'
down_revision: Union[str, Sequence[str], None] = 'a3f14bfa8956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('address', sa.String(), nullable=False))
    op.add_column('applicants', sa.Column('lga_residence', sa.String(), nullable=False))
    op.add_column('applicants', sa.Column('lga_origin', sa.String(), nullable=False))
    op.add_column('applicants', sa.Column('ssce_cert', sa.String(), nullable=False))
    op.add_column('applicants', sa.Column('degree_cert', sa.String(), nullable=False))
    op.add_column('applicants', sa.Column('agree_to_rules', sa.Boolean(), nullable=False))
    op.add_column('applicants', sa.Column('aagree_to_return_properties', sa.Boolean(), nullable=False))
    #op.add_column('applicants', sa.Column('additional_skills', sa.String(), nullable=False))
    op.alter_column('applicants', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('applicants', 'do_you_smoke',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('applicants', 'design_rating',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('applicants', 'additional_skills')
    op.drop_column('applicants', 'local_government_residence')
    op.drop_column('applicants', 'local_government_origin')
    op.drop_column('applicants', 'residential_address')
    op.drop_column('applicants', 'agree_to_return_properties')
    op.drop_column('applicants', 'ssce_certificate')
    op.drop_column('applicants', 'agree_to_abide_rules')
    op.drop_column('applicants', 'higher_education_degree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('higher_education_degree', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('agree_to_abide_rules', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('ssce_certificate', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('agree_to_return_properties', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('residential_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('local_government_origin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('local_government_residence', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('additional_skills', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('applicants', 'design_rating',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('applicants', 'do_you_smoke',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('applicants', 'date_of_birth',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('applicants', 'extra_skills')
    op.drop_column('applicants', 'agree_to_return_props')
    op.drop_column('applicants', 'agree_to_rules')
    op.drop_column('applicants', 'degree_cert')
    op.drop_column('applicants', 'ssce_cert')
    op.drop_column('applicants', 'lga_origin')
    op.drop_column('applicants', 'lga_residence')
    op.drop_column('applicants', 'address')
    # ### end Alembic commands ###
