"""Renamed username to full_name on Admin

Revision ID: a3f14bfa8956
Revises: 14aeace01679
Create Date: 2025-07-24 19:37:23.076910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f14bfa8956'
down_revision: Union[str, Sequence[str], None] = '14aeace01679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('admins_username_key'), 'admins', type_='unique')
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('admins_username_key'), 'admins', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('admins', 'full_name')
    # ### end Alembic commands ###
