"""add_date_fields_and_dashboard_columns_to_existing_officers

Revision ID: bedd41ec9a44
Revises: 2a7e1f165613
Create Date: 2026-01-16 13:16:10.418301

"""
from typing import Sequence, Union
from datetime import date
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bedd41ec9a44'
down_revision: Union[str, Sequence[str], None] = '2a7e1f165613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add columns as NULLABLE first (to handle existing records)
    op.add_column('existing_officers', sa.Column('date_of_enlistment', sa.Date(), nullable=True, comment='Date officer enlisted - REQUIRED'))
    op.add_column('existing_officers', sa.Column('date_of_promotion', sa.Date(), nullable=True, comment='Date of last promotion - OPTIONAL'))
    op.add_column('existing_officers', sa.Column('registration_pdf_path', sa.String(length=500), nullable=True, comment='Path to Existing Officer Registration Form PDF'))
    op.add_column('existing_officers', sa.Column('registration_generated_at', sa.DateTime(timezone=True), nullable=True, comment='When Registration PDF was generated'))
    op.add_column('existing_officers', sa.Column('dashboard_access_count', sa.Integer(), nullable=True, server_default=sa.text('0'), comment='Number of times dashboard accessed'))
    op.add_column('existing_officers', sa.Column('last_dashboard_access', sa.DateTime(timezone=True), nullable=True, comment='Last dashboard access timestamp'))
    
    # 2. Update existing records with a default date (for existing officers)
    # Use a safe default date (e.g., 2020-01-01) for existing records
    op.execute("""
        UPDATE existing_officers 
        SET date_of_enlistment = '2020-01-01'::date 
        WHERE date_of_enlistment IS NULL
    """)
    
    # 3. Now alter the column to NOT NULL
    op.alter_column('existing_officers', 'date_of_enlistment',
                    existing_type=sa.Date(),
                    nullable=False)
    
    # 4. Update column comments
    op.alter_column('existing_officers', 'officer_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Original officer ID from legacy system - NEW FORMAT: PREFIX/ALPHANUMERIC/INTAKE',
               existing_comment='Original officer ID from legacy system',
               existing_nullable=False)
    op.alter_column('existing_officers', 'passport_photo',
               existing_type=sa.VARCHAR(length=255),
               comment='Passport photo path - REQUIRED',
               existing_comment='Passport photo path',
               existing_nullable=True)
    op.alter_column('existing_officers', 'nin_slip',
               existing_type=sa.VARCHAR(length=255),
               comment='NIN slip path - REQUIRED',
               existing_comment='NIN slip path',
               existing_nullable=True)
    op.alter_column('existing_officers', 'ssce_certificate',
               existing_type=sa.VARCHAR(length=255),
               comment='SSCE certificate path - REQUIRED',
               existing_comment='SSCE certificate path',
               existing_nullable=True)
    op.alter_column('existing_officers', 'birth_certificate',
               existing_type=sa.VARCHAR(length=255),
               comment='Birth certificate path - OPTIONAL',
               existing_comment='Birth certificate path',
               existing_nullable=True)
    op.alter_column('existing_officers', 'letter_of_first_appointment',
               existing_type=sa.VARCHAR(length=255),
               comment='First appointment letter - OPTIONAL',
               existing_comment='First appointment letter',
               existing_nullable=True)
    op.alter_column('existing_officers', 'promotion_letters',
               existing_type=sa.VARCHAR(length=255),
               comment='Promotion letters - OPTIONAL',
               existing_comment='Promotion letters',
               existing_nullable=True)
    
    # 5. Create new indexes
    op.create_index('ix_existing_officer_enlistment', 'existing_officers', ['date_of_enlistment'], unique=False)
    
    # 6. Update table comment
    op.create_table_comment(
        'existing_officers',
        'Officers from legacy system with NEW date fields and dashboard tracking',
        existing_comment='Table for officers who registered in the past without payment',
        schema=None
    )
    
    # 7. Check if columns exist before renaming
    inspector = sa.inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('existing_officers')]
    
    if 'application_pdf_path' in columns:
        op.alter_column('existing_officers', 'application_pdf_path',
                       new_column_name='legacy_application_pdf_path',
                       existing_type=sa.VARCHAR(length=500),
                       existing_nullable=True,
                       existing_comment='Legacy: Path to Application Form PDF')
    
    if 'application_generated_at' in columns:
        op.alter_column('existing_officers', 'application_generated_at',
                       new_column_name='legacy_application_generated_at',
                       existing_type=postgresql.TIMESTAMP(timezone=True),
                       existing_nullable=True,
                       existing_comment='Legacy: When Application PDF was generated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Restore renamed columns first
    inspector = sa.inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('existing_officers')]
    
    if 'legacy_application_pdf_path' in columns:
        op.alter_column('existing_officers', 'legacy_application_pdf_path',
                       new_column_name='application_pdf_path',
                       existing_type=sa.VARCHAR(length=500),
                       existing_nullable=True)
    
    if 'legacy_application_generated_at' in columns:
        op.alter_column('existing_officers', 'legacy_application_generated_at',
                       new_column_name='application_generated_at',
                       existing_type=postgresql.TIMESTAMP(timezone=True),
                       existing_nullable=True)
    
    # 2. Restore table comment
    op.create_table_comment(
        'existing_officers',
        'Table for officers who registered in the past without payment',
        existing_comment='Officers from legacy system with NEW date fields and dashboard tracking',
        schema=None
    )
    
    # 3. Drop new index
    op.drop_index('ix_existing_officer_enlistment', table_name='existing_officers')
    
    # 4. Restore column comments
    op.alter_column('existing_officers', 'promotion_letters',
               existing_type=sa.VARCHAR(length=255),
               comment='Promotion letters',
               existing_comment='Promotion letters - OPTIONAL',
               existing_nullable=True)
    op.alter_column('existing_officers', 'letter_of_first_appointment',
               existing_type=sa.VARCHAR(length=255),
               comment='First appointment letter',
               existing_comment='First appointment letter - OPTIONAL',
               existing_nullable=True)
    op.alter_column('existing_officers', 'birth_certificate',
               existing_type=sa.VARCHAR(length=255),
               comment='Birth certificate path',
               existing_comment='Birth certificate path - OPTIONAL',
               existing_nullable=True)
    op.alter_column('existing_officers', 'ssce_certificate',
               existing_type=sa.VARCHAR(length=255),
               comment='SSCE certificate path',
               existing_comment='SSCE certificate path - REQUIRED',
               existing_nullable=True)
    op.alter_column('existing_officers', 'nin_slip',
               existing_type=sa.VARCHAR(length=255),
               comment='NIN slip path',
               existing_comment='NIN slip path - REQUIRED',
               existing_nullable=True)
    op.alter_column('existing_officers', 'passport_photo',
               existing_type=sa.VARCHAR(length=255),
               comment='Passport photo path',
               existing_comment='Passport photo path - REQUIRED',
               existing_nullable=True)
    op.alter_column('existing_officers', 'officer_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Original officer ID from legacy system',
               existing_comment='Original officer ID from legacy system - NEW FORMAT: PREFIX/ALPHANUMERIC/INTAKE',
               existing_nullable=False)
    
    # 5. Make date_of_enlistment nullable before dropping
    op.alter_column('existing_officers', 'date_of_enlistment',
                    existing_type=sa.Date(),
                    nullable=True)
    
    # 6. Drop new columns
    op.drop_column('existing_officers', 'last_dashboard_access')
    op.drop_column('existing_officers', 'dashboard_access_count')
    op.drop_column('existing_officers', 'registration_generated_at')
    op.drop_column('existing_officers', 'registration_pdf_path')
    op.drop_column('existing_officers', 'date_of_promotion')
    op.drop_column('existing_officers', 'date_of_enlistment')
    # ### end Alembic commands ###