"""Add is_verified and is_active to Admin

Revision ID: cdab45db7fd0
Revises: 5f97ccf25305
Create Date: 2025-08-19 12:07:18.636899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdab45db7fd0'
down_revision: Union[str, Sequence[str], None] = '5f97ccf25305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First add columns as nullable
    op.add_column('admins', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE admins SET is_verified = false WHERE is_verified IS NULL")
    op.execute("UPDATE admins SET is_active = false WHERE is_active IS NULL")
    
    # Now alter columns to be NOT NULL
    op.alter_column('admins', 'is_verified', nullable=False)
    op.alter_column('admins', 'is_active', nullable=False)
    
    op.drop_column('officers', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('admins', 'is_active')
    op.drop_column('admins', 'is_verified')
    # ### end Alembic commands ###