"""add existing_officers table

Revision ID: d1668795832a
Revises: 82b41e8404ca
Create Date: 2026-01-13 11:29:34.493241

"""
from typing import Sequence, Union  # ADD THIS LINE
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd1668795832a'
down_revision: Union[str, Sequence[str], None] = '82b41e8404ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # CREATE THE NEW TABLE ONLY
    op.create_table('existing_officers',
        sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the existing officer'),
        sa.Column('officer_id', sa.String(length=50), nullable=False, comment='Original officer ID from legacy system'),
        sa.Column('email', sa.String(length=255), nullable=False, comment='Officer email'),
        sa.Column('phone', sa.String(length=20), nullable=False, comment='Officer phone number'),
        sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password'),
        sa.Column('is_verified', sa.Boolean(), nullable=True, comment='Whether officer credentials are verified'),
        sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True, comment='Date when officer was verified'),
        sa.Column('verified_by', sa.String(length=100), nullable=True, comment='Admin who verified the officer'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, verified, approved, rejected'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether officer account is active'),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Last login timestamp'),
        sa.Column('full_name', sa.String(length=100), nullable=False, comment='Full name'),
        sa.Column('nin_number', sa.String(length=20), nullable=False, comment='National Identification Number'),
        sa.Column('gender', sa.String(length=10), nullable=False, comment='Gender'),
        sa.Column('date_of_birth', sa.Date(), nullable=False, comment='Date of birth'),
        sa.Column('place_of_birth', sa.String(length=100), nullable=False, comment='Place of birth'),
        sa.Column('nationality', sa.String(length=50), nullable=False, comment='Nationality'),
        sa.Column('marital_status', sa.String(length=20), nullable=False, comment='Marital status'),
        sa.Column('residential_address', sa.Text(), nullable=False, comment='Residential address'),
        sa.Column('state_of_residence', sa.String(length=50), nullable=False, comment='State of residence'),
        sa.Column('local_government_residence', sa.String(length=50), nullable=False, comment='LGA of residence'),
        sa.Column('country_of_residence', sa.String(length=50), nullable=False, comment='Country of residence'),
        sa.Column('state_of_origin', sa.String(length=50), nullable=False, comment='State of origin'),
        sa.Column('local_government_origin', sa.String(length=50), nullable=False, comment='LGA of origin'),
        sa.Column('rank', sa.String(length=50), nullable=False, comment='Officer rank'),
        sa.Column('position', sa.String(length=100), nullable=False, comment='Position/title'),
        sa.Column('years_of_service', sa.String(length=20), nullable=True, comment='Years of service'),
        sa.Column('service_number', sa.String(length=50), nullable=True, comment='Service number'),
        sa.Column('religion', sa.String(length=30), nullable=True, comment='Religion'),
        sa.Column('additional_skills', sa.Text(), nullable=True, comment='Additional skills'),
        sa.Column('bank_name', sa.String(length=100), nullable=True, comment='Bank name'),
        sa.Column('account_number', sa.String(length=20), nullable=True, comment='Bank account number'),
        sa.Column('passport_photo', sa.String(length=255), nullable=True, comment='Passport photo path'),
        sa.Column('nin_slip', sa.String(length=255), nullable=True, comment='NIN slip path'),
        sa.Column('ssce_certificate', sa.String(length=255), nullable=True, comment='SSCE certificate path'),
        sa.Column('birth_certificate', sa.String(length=255), nullable=True, comment='Birth certificate path'),
        sa.Column('letter_of_first_appointment', sa.String(length=255), nullable=True, comment='First appointment letter'),
        sa.Column('promotion_letters', sa.String(length=255), nullable=True, comment='Promotion letters'),
        sa.Column('service_certificate', sa.String(length=255), nullable=True, comment='Service certificate'),
        sa.Column('medical_certificate', sa.String(length=255), nullable=True, comment='Medical certificate'),
        sa.Column('guarantor_form', sa.String(length=255), nullable=True, comment='Guarantor form'),
        sa.Column('other_documents', sa.Text(), nullable=True, comment='Other documents JSON array'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=True, comment='Who created this record'),
        sa.Column('updated_by', sa.String(length=100), nullable=True, comment='Who last updated this record'),
        sa.Column('admin_notes', sa.Text(), nullable=True, comment='Administrator notes'),
        sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Reason for rejection if applicable'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('nin_number'),
        sa.UniqueConstraint('officer_id'),
        sa.UniqueConstraint('service_number'),
        comment='Table for officers who registered in the past without payment'
    )
    
    # Create indexes for better performance
    op.create_index(op.f('ix_existing_officers_id'), 'existing_officers', ['id'], unique=False)
    op.create_index(op.f('ix_existing_officers_officer_id'), 'existing_officers', ['officer_id'], unique=True)
    op.create_index(op.f('ix_existing_officers_email'), 'existing_officers', ['email'], unique=True)
    op.create_index(op.f('ix_existing_officers_status'), 'existing_officers', ['status'], unique=False)
    op.create_index(op.f('ix_existing_officers_nin_number'), 'existing_officers', ['nin_number'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_existing_officers_nin_number'), table_name='existing_officers')
    op.drop_index(op.f('ix_existing_officers_status'), table_name='existing_officers')
    op.drop_index(op.f('ix_existing_officers_email'), table_name='existing_officers')
    op.drop_index(op.f('ix_existing_officers_officer_id'), table_name='existing_officers')
    op.drop_index(op.f('ix_existing_officers_id'), table_name='existing_officers')
    
    # Drop table
    op.drop_table('existing_officers')
    # ### end Alembic commands ###