"""add passport field

Revision ID: d40af2d206fa
Revises: 954a001f9cb5
Create Date: 2025-08-03 17:11:30.773387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40af2d206fa'
down_revision: Union[str, Sequence[str], None] = '954a001f9cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', 
        sa.Column('passport', 
            sa.String(length=255), 
            nullable=True,
            comment='Path to officer passport photo'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'passport')
    # ### end Alembic commands ###