"""payment table

Revision ID: e06fbddb7120
Revises: bedd41ec9a44
Create Date: 2026-01-17 15:56:06.197516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06fbddb7120'
down_revision: Union[str, Sequence[str], None] = 'bedd41ec9a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ONLY create the payments table - DO NOT modify existing_officers
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=False),
    sa.Column('authorization_url', sa.Text(), nullable=True),
    sa.Column('access_code', sa.String(), nullable=True),
    sa.Column('estech_share', sa.Integer(), nullable=True),
    sa.Column('marshal_share', sa.Integer(), nullable=True),
    sa.Column('estech_paid_out', sa.Boolean(), nullable=True),
    sa.Column('estech_payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estech_payout_reference', sa.String(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('verification_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for the payments table
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_payments_user_email'), 'payments', ['user_email'], unique=False)
    
    # That's it! No changes to existing_officers table
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ONLY drop the payments table - leave existing_officers untouched
    op.drop_index(op.f('ix_payments_user_email'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_table('payments')
    
    # ### end Alembic commands ###