"""add_officer_fields

Revision ID: f3165f415aae
Revises: 914ed5b57440
Create Date: 2025-08-04 12:23:28.861356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3165f415aae'
down_revision: Union[str, Sequence[str], None] = '914ed5b57440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('local_government_origin', sa.String(length=50), nullable=True))
    op.drop_column('officers', 'higher_education_certificate')
    op.drop_column('officers', 'nin_slip')
    op.drop_column('officers', 'ssce_certificate')
    op.drop_column('officers', 'lga_of_origin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('lga_of_origin', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('officers', sa.Column('ssce_certificate', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('officers', sa.Column('nin_slip', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('officers', sa.Column('higher_education_certificate', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('officers', 'local_government_origin')
    # ### end Alembic commands ###
